name: Build

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v5

      - name: Compile LaTeX document
        run: make

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resume
          path: gabriele_bocchi_resume.pdf
