name: Build

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest@sha256:2895fb163c63e5e0276a543b1ca89884cce86cb004b1c5e6b061f5c82709bd73

    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Compile LaTeX document
        run: make

      - name: Create artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          path: gabriele_bocchi_resume.pdf
          archive: false
