name: Release

on:
  push:
    tags:
      - "v*-*-*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest@sha256:2895fb163c63e5e0276a543b1ca89884cce86cb004b1c5e6b061f5c82709bd73

    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Compile LaTeX document
        run: make

      - name: Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          files: gabriele_bocchi_resume.pdf
