name: Release

on:
  push:
    tags:
      - "v*-*-*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest@sha256:f0bc49733665c09378b8ec0aca40e3263211bd208c9ecb7dfcce4967f234cf49

    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Compile LaTeX document
        run: make

      - name: Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          files: gabriele_bocchi_resume.pdf
